// Code generated by kanban/gen. DO NOT EDIT.

package banner

// Version ...
var Version = "v1.0.0-test"

// Copyright ...
var Copyright = "© 2020 - 2026 FloatTech"

// Banner ...
var Banner = "* OneBot + ZeroBot + Golang\n" +
	"* Version " + Version + " - 2026-04-30 09:38:01 +0800 CST\n" +
	"* Copyright " + Copyright + ". All Rights Reserved.\n" +
	"* Project: https://github.com/FloatTech/ZeroBot-Plugin"
